### ISSUE TITLE
Crash when entering empty command ':'

### ISSUE THREAD

**Issue by sinopeus** [NorfairKing/hacyc#2]

**Comment by NorfairKing** [comment]
I can't seem to reproduce this.
I get this: `Hacyc > Search > ""`

**Comment by sinopeus** [comment]
That's not what I meant. Open hacyc, just type ":" and see what happens. I get the same as you when I do ": s".

**Comment by NorfairKing** [comment]
I don't have a problem there. It just opens the command bar.

**Comment by sinopeus** [comment]
Dude. Type ":". Press enter.

**Comment by NorfairKing** [comment]
Aha! Now I got it!, marking this as a bug.
